version: "3"
services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - server-network
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=bradery
    ports:
      - 3306:3306
  cache:
    image: redis:latest
    restart: unless-stopped
    networks:
      - server-network
    ports:
      - 6379:6379
  backend:
    build: ./backend-service-ecommerce
    ports:
      - 3001:3001
    restart: unless-stopped
    networks:
      - server-network
    depends_on:
      - db
      - cache
    environment:
      - TYPEORM_HOST=db
      - TYPEORM_PORT=3306
      - TYPEORM_USERNAME=root
      - TYPEORM_PASSWORD=
      - TYPEORM_DATABASE=bradery
      - REDIS_URL=redis://cache:6379
      - REDIS_HOST=cache
  frontend:
    build: ./frontend-service-ecommerce
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    networks:
      - server-network
networks:
  server-network:
