version: "3"
services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  cache:
    image: redis:latest
    restart: unless-stopped
    networks:
      - default
    ports:
      - 6379:6379
  backend:
    build: ./backend-service-ecommerce
    ports:
      - 3001:3000
    restart: unless-stopped
    networks:
      - default
    depends_on:
      - db
      - cache
    environment:
      - TYPEORM_HOST=db
      - TYPEORM_PORT=3306
      - TYPEORM_USERNAME=root
      - TYPEORM_PASSWORD=root
      - TYPEORM_DATABASE=bradery
      - REDIS_URL=redis://cache:6379
      - REDIS_HOST=cache
  frontend:
    build: ./frontend-service-ecommerce
    ports:
      - 3000:3000
    environment:
      - API_URL=http://backend:3001
    networks:
      - default
